//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMartket_System_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pos
    {
        public string MaPos { get; set; }
        public string TenPos { get; set; }
        public string SoSeri { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayLapDat { get; set; }
        public Nullable<System.DateTime> LastMaintenance { get; set; }
        public int MaNhanVien { get; set; }
        public int MaCuaHang { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
