//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMartket_System_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLCaNV
    {
        public int MaQLCa { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
        public int MaCongThuHai { get; set; }
        public int MaCongThuBa { get; set; }
        public int MaCongThuTu { get; set; }
        public int MaCongThuNam { get; set; }
        public int MaCongThuSau { get; set; }
        public int MaCongThuBay { get; set; }
        public int MaCongChuNhat { get; set; }
    
        public virtual Cong Cong { get; set; }
        public virtual Cong Cong1 { get; set; }
        public virtual Cong Cong2 { get; set; }
        public virtual Cong Cong3 { get; set; }
        public virtual Cong Cong4 { get; set; }
        public virtual Cong Cong5 { get; set; }
        public virtual Cong Cong6 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
